### ISSUE TITLE
Research GitHub API

### ISSUE THREAD

**Issue by AustinBQ02** [SeanAllen19/GIT-IDEAS#2]
What options are available on the GitHub API?

- What can we search by?
- What do results look like?

What documentation is available?
-  word

<br>

**Comment by Re-Gi** [comment]
The GraphQL API returns exactly the data that you request. GraphQL also returns the data in a pre-known structure based on your request. In contrast, the REST API returns more data than you requested and returns it in a pre-determined structure. You can also accomplish the equivalent of multiple REST API request in a single GraphQL request. The ability to make fewer requests and fetch less data makes GraphQL appealing to developers of mobile applications.

**Comment by Re-Gi** [comment]
https://docs.github.com/en/developers/overview/about-githubs-apis#choosing-the-graphql-api

**Comment by SeanAllen19** [comment]
https://api.github.com/

**Comment by SeanAllen19** [comment]
This allows us to play with the api directly

**Comment by brettnachman** [comment]
Need to understand the GraphQL vs Rest syntax and whether both can meet readme reqs

**Comment by Re-Gi** [comment]
https://docs.github.com/en/graphql/guides/forming-calls-with-graphql#the-graphql-endpoint

Forming Calls with GraphQL

**Comment by Re-Gi** [comment]
On sending HTTP requests with GraphQL:

The two types of allowed operations in GitHub's GraphQL API are queries and mutations. Comparing GraphQL to REST, queries operate like GET requests, while mutations operate like POST/PATCH/DELETE. The [mutation name](https://docs.github.com/en/graphql/reference/mutations) determines which modification is executed.

**Comment by SeanAllen19** [comment]
https://www.youtube.com/watch?v=7YeOjmpQUnU

Github Search Users By Username in Javascript

**Comment by Re-Gi** [comment]
Send GraphQL queries with the Fetch API:

https://www.netlify.com/blog/2020/12/21/send-graphql-queries-with-the-fetch-api-without-using-apollo-urql-or-other-graphql-clients/

**Comment by brettnachman** [comment]
https://docs.github.com/en/rest/guides/scripting-with-the-rest-api-and-javascript?apiVersion=2022-11-28

**Comment by SeanAllen19** [comment]
https://www.npmjs.com/package/axios

**Comment by brettnachman** [comment]
octokit.js repository/documentation: 

https://github.com/octokit/octokit.js/#usage

**Comment by Re-Gi** [comment]
Use the REST API to search for specific items on GitHub:

https://docs.github.com/en/rest/search?apiVersion=2022-11-28#about-search
