### ISSUE TITLE
Research Axios

### ISSUE THREAD

**Issue by AustinBQ02** [SeanAllen19/GIT-IDEAS#5]
https://www.npmjs.com/package/axios

- what is it? 
- how can we use it?
- any examples?

Getting Started (from Axios)
 - https://axios-http.com/docs/intro

Post Requests:
- https://axios-http.com/docs/post_example

Get Requests:
- https://www.educative.io/answers/how-to-make-an-axios-get-request

**Comment by brettnachman** [comment]
HTTP Requests with Axios Tutorial: 

https://youtu.be/rzGGK7BHCAA

Blog Post: 

https://blog.logrocket.com/how-to-make-http-requests-like-a-pro-with-axios/

**Comment by brettnachman** [comment]
HTTP Requests with Axios: 

https://circleci.com/blog/making-http-requests-with-axios/

**Comment by brettnachman** [comment]
Get and Post using Axios: 

https://zetcode.com/javascript/axios/

**Comment by brettnachman** [comment]
Getting Started (from Axios)

https://axios-http.com/docs/intro

Post Requests: 

https://axios-http.com/docs/post_example

Get Requests:

https://www.educative.io/answers/how-to-make-an-axios-get-request
