### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by AustinBQ02** [SeanAllen19/GIT-IDEAS#56]
Remove defunct code blocks that have been commented out. 
Add descriptive comments as needed.

Michael:

- [x] Models
- [x] Seeds
- [x] Server.js 
- [x] anything with tags

Rebecca:

- [x] Controllers
- [x] Templates

Brett

- [x] public / js

**Comment by Re-Gi** [comment]
Empty files to be considered for deletion:  
- exploreRoutes.js
- notableResults.handlebars

Unused files, but possibly useful for future development:  
- explore.handlebars
- navbar.handlebars

Unused code, but possible useful for future development:  
- homeRoutes.js > `router.get("/explore")`
  -Finds all notes in the database along with associated tag data and username. Insomnia tested.

**Comment by AustinBQ02** [comment]
Completed in PR #58 #59 #60
