### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by AustinBQ02** [SeanAllen19/GIT-IDEAS#8]
Outline /design of basic landing page so we can start creating handlebar templates

**Comment by SeanAllen19** [comment]
https://www.figma.com/file/mwsn2mHLZPHB42zZqtvbBk/DASHBOARD?node-id=0%3A1&t=HdZNrnlOtZghV0gv-0

We talked about how the pages should be set up. We had lot of ideas to try and create but we winded up editing the pages as we developed them.
